# Generated by Django 2.0.13 on 2020-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(upload_to='usr'),
        ),
    ]
