# Generated by Django 2.0.13 on 2020-06-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200605_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='usr')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
    ]
